//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParaglidingWeather.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Directions_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Directions_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ParaglidingWeather.Resources.Directions.ru", typeof(Directions_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        public static string NorthByEast {
            get {
                return ResourceManager.GetString("NorthByEast", resourceCulture);
            }
        }
        
        public static string NorthNortheast {
            get {
                return ResourceManager.GetString("NorthNortheast", resourceCulture);
            }
        }
        
        public static string NortheastByNorth {
            get {
                return ResourceManager.GetString("NortheastByNorth", resourceCulture);
            }
        }
        
        public static string Northeast {
            get {
                return ResourceManager.GetString("Northeast", resourceCulture);
            }
        }
        
        public static string NortheastByEast {
            get {
                return ResourceManager.GetString("NortheastByEast", resourceCulture);
            }
        }
        
        public static string EastNortheast {
            get {
                return ResourceManager.GetString("EastNortheast", resourceCulture);
            }
        }
        
        public static string EastByNorth {
            get {
                return ResourceManager.GetString("EastByNorth", resourceCulture);
            }
        }
        
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        public static string EastBySouth {
            get {
                return ResourceManager.GetString("EastBySouth", resourceCulture);
            }
        }
        
        public static string EastSoutheast {
            get {
                return ResourceManager.GetString("EastSoutheast", resourceCulture);
            }
        }
        
        public static string SoutheastByEast {
            get {
                return ResourceManager.GetString("SoutheastByEast", resourceCulture);
            }
        }
        
        public static string Southeast {
            get {
                return ResourceManager.GetString("Southeast", resourceCulture);
            }
        }
        
        public static string SoutheastBySouth {
            get {
                return ResourceManager.GetString("SoutheastBySouth", resourceCulture);
            }
        }
        
        public static string SouthSoutheast {
            get {
                return ResourceManager.GetString("SouthSoutheast", resourceCulture);
            }
        }
        
        public static string SouthByEast {
            get {
                return ResourceManager.GetString("SouthByEast", resourceCulture);
            }
        }
        
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        public static string SouthByWest {
            get {
                return ResourceManager.GetString("SouthByWest", resourceCulture);
            }
        }
        
        public static string SouthSouthwest {
            get {
                return ResourceManager.GetString("SouthSouthwest", resourceCulture);
            }
        }
        
        public static string SouthwestBySouth {
            get {
                return ResourceManager.GetString("SouthwestBySouth", resourceCulture);
            }
        }
        
        public static string Southwest {
            get {
                return ResourceManager.GetString("Southwest", resourceCulture);
            }
        }
        
        public static string SouthwestByWest {
            get {
                return ResourceManager.GetString("SouthwestByWest", resourceCulture);
            }
        }
        
        public static string WestSouthwest {
            get {
                return ResourceManager.GetString("WestSouthwest", resourceCulture);
            }
        }
        
        public static string WestBySouth {
            get {
                return ResourceManager.GetString("WestBySouth", resourceCulture);
            }
        }
        
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
        
        public static string WestByNorth {
            get {
                return ResourceManager.GetString("WestByNorth", resourceCulture);
            }
        }
        
        public static string WestNorthwest {
            get {
                return ResourceManager.GetString("WestNorthwest", resourceCulture);
            }
        }
        
        public static string NorthwestByWest {
            get {
                return ResourceManager.GetString("NorthwestByWest", resourceCulture);
            }
        }
        
        public static string Northwest {
            get {
                return ResourceManager.GetString("Northwest", resourceCulture);
            }
        }
        
        public static string NorthwestByNorth {
            get {
                return ResourceManager.GetString("NorthwestByNorth", resourceCulture);
            }
        }
        
        public static string NorthNorthwest {
            get {
                return ResourceManager.GetString("NorthNorthwest", resourceCulture);
            }
        }
        
        public static string NorthByWest {
            get {
                return ResourceManager.GetString("NorthByWest", resourceCulture);
            }
        }
    }
}
